








include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: error 
    deprecated_member_use: warning 
linter:
  
  
  
  
  
  
  
  
  
  
  rules:
    - avoid_print 
    - file_names 
    - camel_case_types
    - avoid_empty_else 
    
    


