// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXwUiumKi9c4ScRKncXHOw3wl29DJtUM',
    appId: '1:408916913896:web:87c9520eb09945fd3de35d',
    messagingSenderId: '408916913896',
    projectId: 'locationbasedinformationshare',
    authDomain: 'locationbasedinformationshare.firebaseapp.com',
    storageBucket: 'locationbasedinformationshare.appspot.com',
    measurementId: 'G-FC0K8JFBCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sncMWjOXeOfBP3ZZ01hewTzraQLF50M',
    appId: '1:408916913896:android:1c2d54a54349f41c3de35d',
    messagingSenderId: '408916913896',
    projectId: 'locationbasedinformationshare',
    storageBucket: 'locationbasedinformationshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUA8wD7j5H8KcGmGPH841frSPb7-baJA',
    appId: '1:408916913896:ios:45ffb3253bff76f63de35d',
    messagingSenderId: '408916913896',
    projectId: 'locationbasedinformationshare',
    storageBucket: 'locationbasedinformationshare.appspot.com',
    iosBundleId: 'com.example.locationSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoUA8wD7j5H8KcGmGPH841frSPb7-baJA',
    appId: '1:408916913896:ios:7c9aee1d18e3bddd3de35d',
    messagingSenderId: '408916913896',
    projectId: 'locationbasedinformationshare',
    storageBucket: 'locationbasedinformationshare.appspot.com',
    iosBundleId: 'com.example.locationSocialMedia.RunnerTests',
  );
}
